# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import stt_pb2 as stt__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in stt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class STTServiceStub(object):
    """The STT service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendSTTResult = channel.unary_unary(
                '/stt.STTService/SendSTTResult',
                request_serializer=stt__pb2.STTResult.SerializeToString,
                response_deserializer=stt__pb2.STTResponse.FromString,
                _registered_method=True)
        self.ProcessAudioFile = channel.unary_unary(
                '/stt.STTService/ProcessAudioFile',
                request_serializer=stt__pb2.AudioFileRequest.SerializeToString,
                response_deserializer=stt__pb2.STTResponse.FromString,
                _registered_method=True)


class STTServiceServicer(object):
    """The STT service definition
    """

    def SendSTTResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessAudioFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_STTServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendSTTResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSTTResult,
                    request_deserializer=stt__pb2.STTResult.FromString,
                    response_serializer=stt__pb2.STTResponse.SerializeToString,
            ),
            'ProcessAudioFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessAudioFile,
                    request_deserializer=stt__pb2.AudioFileRequest.FromString,
                    response_serializer=stt__pb2.STTResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stt.STTService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stt.STTService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class STTService(object):
    """The STT service definition
    """

    @staticmethod
    def SendSTTResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stt.STTService/SendSTTResult',
            stt__pb2.STTResult.SerializeToString,
            stt__pb2.STTResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessAudioFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stt.STTService/ProcessAudioFile',
            stt__pb2.AudioFileRequest.SerializeToString,
            stt__pb2.STTResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
