services:
  rabbitmq:
    image: rabbitmq:management
    container_name: messaging-service
    ports:
      - "5672:5672"
      - "8080:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
