// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audio.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteAudio = `-- name: DeleteAudio :exec
DELETE FROM Audio
WHERE id = $1
`

func (q *Queries) DeleteAudio(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAudio, id)
	return err
}

const getAudioById = `-- name: GetAudioById :one
SELECT id, name, extension, mime_type, path
FROM Audio
WHERE id = $1
`

func (q *Queries) GetAudioById(ctx context.Context, id uuid.UUID) (Audio, error) {
	row := q.db.QueryRow(ctx, getAudioById, id)
	var i Audio
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Extension,
		&i.MimeType,
		&i.Path,
	)
	return i, err
}

const insertAudio = `-- name: InsertAudio :one
INSERT INTO Audio (id, name, extension, mime_type, path)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, extension, mime_type, path
`

type InsertAudioParams struct {
	ID        uuid.UUID
	Name      string
	Extension string
	MimeType  string
	Path      string
}

func (q *Queries) InsertAudio(ctx context.Context, arg InsertAudioParams) (Audio, error) {
	row := q.db.QueryRow(ctx, insertAudio,
		arg.ID,
		arg.Name,
		arg.Extension,
		arg.MimeType,
		arg.Path,
	)
	var i Audio
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Extension,
		&i.MimeType,
		&i.Path,
	)
	return i, err
}

const listAudios = `-- name: ListAudios :many
SELECT id, name, extension, mime_type, path
FROM Audio
ORDER BY name
`

func (q *Queries) ListAudios(ctx context.Context) ([]Audio, error) {
	rows, err := q.db.Query(ctx, listAudios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Audio
	for rows.Next() {
		var i Audio
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Extension,
			&i.MimeType,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAudioPath = `-- name: UpdateAudioPath :exec
UPDATE Audio
SET path = $2
WHERE id = $1
`

type UpdateAudioPathParams struct {
	ID   uuid.UUID
	Path string
}

func (q *Queries) UpdateAudioPath(ctx context.Context, arg UpdateAudioPathParams) error {
	_, err := q.db.Exec(ctx, updateAudioPath, arg.ID, arg.Path)
	return err
}
